export const USERCREATEREQUEST = "USERCREATEREQUEST"
export const USERCREATESUCCEESS = "USERCREATESUCCEESS"
export const USERCREATEFALIURE = "USERCREATEFALIURE"

export const GETALLUSERSREQUEST = "GETALLUSERSREQUEST"
export const GETALLUSERSSUCCESS = "GETALLUSERSSUCCESS"
export const GETALLUSERSFALIURE = "GETALLUSERSFALIURE"

export const EDITUSERREQUEST = "EDITUSERREQUEST"
export const EDITUSERSUCCESS = "EDITUSERSUCCESS"
export const EDITUSERFALIURE = "EDITUSERFALIURE"

export const DELETEUSERREQUEST = "DELETEUSERREQUEST"
export const DELETEUSERSUCCEESS = "DELETEUSERSUCCEESS"
export const DELETEUSERFALIURE = "DELETEUSERFALIURE"